apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: default
data:
  DATABASE_URL: "jdbc:postgresql://db-service:5432/oficina"
  DATABASE_USER: "postgres"
  ADMIN_USERNAME: "admin"
  JWT_EXPIRATION_MS: "86400000"
