apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_PASS: "postgres"
  ADMIN_PASSWORD: "admin123"
  JWT_SECRET: "substituir-por-uma-chave-segura-em-producao-k8s-secret"
